name: HLP_Stack
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _py-xgboost-mutex=2.0=gpu_0
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h2019614_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.13=hb9d3cd8_0
  - anyio=4.5.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h01eb140_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_2
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.2.0=pyh71513ae_0
  - autodock=4.2.6=h9948957_4
  - babel=2.16.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bedtools=2.31.1=hf5e1c6e_2
  - biopython=1.83=py38h01eb140_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - blosc=1.21.5=h0f2a231_0
  - boto3=1.34.154=py38h06a4308_0
  - botocore=1.34.154=py38h06a4308_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py38hfa26641_8
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.0=pyhd8ed1ab_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.17.0=py38heb5c249_0
  - chardet=5.2.0=py38h578d9bd_1
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.1.1=py38h7f3f72f_1
  - cpython=3.8.20=py38hd8ed1ab_2
  - cryptography=43.0.0=py38hf793753_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.5=py38h6d02427_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.8=py38h06a4308_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.4=h5888daf_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - flatbuffers=23.5.26=h59595ed_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py38h2019614_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozenlist=1.4.1=py38h01eb140_0
  - gast=0.5.5=pyhd8ed1ab_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gffread=0.12.7=hdcf5f25_4
  - giflib=5.2.2=hd590300_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - glm=0.9.9.8=h00ab1b0_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py38h6a1700d_1
  - google-auth=2.35.0=pyhff2d567_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - graphite2=1.3.13=h59595ed_1003
  - greenlet=3.0.3=py38h17151c0_0
  - grpcio=1.54.3=py38h8dc9893_0
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.11.0=nompi_py38h55b5aab_102
  - harfbuzz=8.5.0=hfac3d4d_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=py38h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py38h578d9bd_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - kagglehub=0.2.7=py38h06a4308_0
  - keras=2.13.1=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=20_linux64_openblas
  - libboost=1.84.0=hba137d9_3
  - libboost-python=1.84.0=py38haa4b4a7_5
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=20_linux64_openblas
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.7=default_h087397f_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.80.2=hf974151_0
  - libglu=9.0.0=hac7e632_1003
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.51=hbd13f7d_1
  - libgrpc=1.54.3=hb20ce57_0
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=20_linux64_openblas
  - liblightgbm=4.5.0=cuda_h1f3617d_3
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.7=hb77312f_0
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libmagma=2.7.1=hc72dce7_6
  - libmagma_sparse=2.7.1=h8354cda_6
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.58.0=h47da74e_1
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.43=h2797004_0
  - libpq=16.6=h035377e_1
  - libprotobuf=3.21.12=hfc55251_2
  - librdkit=2024.03.5=h79cfef2_3
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=256.9=h2774228_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.15=h0b41bf4_0
  - libxgboost=2.1.1=cuda118_h09a87be_2
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.12.7=hc051c1a_1
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - lightgbm=4.5.0=cuda_py_3
  - llvm-openmp=19.1.7=h024ca30_0
  - lz4-c=1.9.4=hcb278e6_0
  - magma=2.7.1=ha770c72_6
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib=3.7.3=py38h578d9bd_0
  - matplotlib-base=3.7.3=py38h58ed7fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2022.2.1=h6508926_16999
  - mmcif_pdbx=2.0.1=pyhd8ed1ab_0
  - molvs=0.1.1=py_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.5=py38h01eb140_0
  - multiprocess=0.70.15=py38h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhff2d567_2
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nccl=2.24.3.1=h03a54cd_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - nspr=4.36=h5888daf_0
  - nss=3.100=hca3bf56_0
  - numpy=1.24.4=py38h59b608b_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openbabel=3.1.1=py38h8a87c98_9
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.4.1=h7b32b05_0
  - opt_einsum=3.4.0=pyhd8ed1ab_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.0.3=py38h01efb38_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pathos=0.3.0=py38h06a4308_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pdb2pqr=3.6.1=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py38h9e66945_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - pmw=2.0.1=py38h578d9bd_1008
  - pooch=1.8.2=pyhd8ed1ab_0
  - pox=0.3.3=py38h06a4308_0
  - ppft=1.7.6.7=py38h06a4308_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - propka=3.5.1=pyhc1e730c_1
  - protobuf=4.21.12=py38h8dc9893_0
  - protobuf3-to-dict=0.1.5=py38h578d9bd_9
  - psutil=6.0.0=py38hfb59056_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-xgboost=2.1.1=cuda118_pyhf54b869_2
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycairo=1.26.1=py38he403b34_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyfaidx=0.8.1.3=pyhdfd78af_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pymol-open-source=3.0.0=py38hfaa11ac_8
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.9=py38hffdaa6c_5
  - pyqt5-sip=12.12.2=py38h17151c0_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - pyyaml=6.0.2=py38h2019614_0
  - pyzmq=26.2.0=py38h6c80b9a_0
  - qt-main=5.15.8=hc9dc06e_21
  - rdkit=2024.03.5=py38h890d753_3
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h5eee18b_0
  - reduce=4.14=py38hfe239e1_2
  - referencing=0.35.1=pyhd8ed1ab_0
  - reportlab=4.2.2=py38hfb59056_0
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - rpds-py=0.20.0=py38h4005ec7_0
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.10.1=py38h06a4308_0
  - sagemaker=2.75.1=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py38ha25d942_2
  - scipy=1.10.1=py38h59b608b_3
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sip=6.7.12=py38h17151c0_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.7=h1b44611_2
  - smdebug-rulesconfig=1.0.1=pyhd3deb0d_1
  - snappy=1.1.10=hdb0a2a9_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.24=py38h01eb140_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py38h7f0c24c_0
  - sympy=1.13.3=pyh2585a3b_104
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.13.0=hceb3a55_1
  - tensorboard=2.13.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38hcdda232_1
  - tensorflow=2.13.1=cuda118py38h409af0c_1
  - tensorflow-base=2.13.1=cuda118py38h52ca5c6_1
  - tensorflow-estimator=2.13.1=cuda118py38ha2f8a09_1
  - termcolor=2.4.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - tornado=6.4.1=py38hfb59056_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py38h01eb140_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=1.26.19=py38h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - werkzeug=3.0.6=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - wrapt=1.16.0=py38h01eb140_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xgboost=2.1.1=cuda118_pyh98e67c5_2
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py38h01eb140_0
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py38h62bed22_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - crepes==0.8.0
      - fsspec==2025.3.0
      - gensim==4.3.3
      - huggingface-hub==0.30.2
      - networkx==3.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - pybedtools==0.12.0
      - pysam==0.23.0
      - regex==2024.11.6
      - safetensors==0.5.3
      - selfies==2.2.0
      - smart-open==7.1.0
      - tokenizers==0.20.3
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - transformers==4.46.3
      - triton==3.0.0
      - typing-extensions==4.12.2
